title: Translations devroom at FOSDEM'26
description: Join the room and boost libre localization efforts!
show_downloads: false
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
